function [p,d_in,r_o    ,r_in,A,delta_glass,delta_insul,delta_abs,delta_air,cp_glass,cp_ins,rho_glass,rho_insul,alpha,tau_alpha, k_insul,cp_abs,rho_abs,cp_air]= get_constants
p=.127;                 % tube pitch (m)
d_in=9.5/1000;          % tube inner diameter(m)
r_o=5/1000;             % tube outer radius(m)
r_in=d_in/2;            % tube inner radius(m)
A=pi*r_in^2;            % flow area(sqm)
delta_glass=3.81/1000;  % glass cover thickness
delta_insul=50.8/1000;  % insulation thickness(m)
delta_abs=.015;         % absorber thickness(m)
delta_air=.025;         % air gap thickness(m)
cp_glass=720;           % cover specific heat (J/kg.K)
cp_ins=1030;            % insulation specific heat (J/kg.K)
rho_glass=2500;         % cover density(Kg/m^3)
rho_insul=70;           % insulation density(Kg/m^3)
alpha=.005;             % absorption coefficient;
tau_alpha=.861;         % effictive transmittance-absorption coef.
k_insul=0.035;          % insulation thermal conductivity(W/m.K)
cp_abs =385;            % absorber specific heat (J/kg.K)
rho_abs =8795;          % absorber density(Kg/m^3)
cp_air=1.0056e+003;     % air specific heat (J/kg.K)
end